AWSTemplateFormatVersion: '2010-09-09'
Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: taskmanagerfrontbread12
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join ['', ['arn:aws:s3:::', !Ref FrontendBucket, '/*']]

Outputs:
  WebsiteURL:
    Description: URL for the website
    Value: !GetAtt FrontendBucket.WebsiteURL
